# Generated by Django 6.0.1 on 2026-07-14 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skillapp_core_curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='submissions/photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='submissions/videos/')),
                ('learner_note_text', models.TextField(blank=True)),
                ('learner_audio', models.FileField(blank=True, null=True, upload_to='submissions/audio/')),
                ('learner_audio_transcript', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Waiting for review'), ('approved', 'Approved'), ('needs_changes', 'Needs changes')], default='pending', max_length=20)),
                ('first_submitted_at', models.DateTimeField(auto_now_add=True)),
                ('last_submitted_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('feedback_text', models.TextField(blank=True)),
                ('feedback_audio', models.FileField(blank=True, null=True, upload_to='submissions/feedback_audio/')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_submissions', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='skillapp_core_curriculum.milestone')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('learner', 'milestone'), name='unique_learner_milestone_submission')],
            },
        ),
    ]
