# Generated by Django 5.2.5 on 2026-01-07 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_initial'),
        ('repository', '0001_initial'),
        ('users', '0002_student_stars'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='completionrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='completionrecord',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completion_records', to='learning.assignment'),
        ),
        migrations.AlterUniqueTogether(
            name='completionrecord',
            unique_together={('student', 'programme', 'unit', 'resource', 'assignment')},
        ),
    ]
