# Generated by Django 5.2.5 on 2026-03-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_alter_completionrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='audio',
            field=models.FileField(blank=True, upload_to='learning/submissions/audio/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='audio_transcript',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='text_response',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='content_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
