# Generated by Django 5.2.5 on 2026-01-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_payment_academic_year_payment_trimester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='academic_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='trimester',
            field=models.IntegerField(),
        ),
    ]
