# Generated by Django 5.2.5 on 2026-03-22 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_initial'),
        ('learning', '0007_alter_completionrecord_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRevisionKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic_title', models.CharField(max_length=255)),
                ('trigger_phrases', models.TextField(blank=True, help_text='Comma-separated student phrases or keywords that should map to this topic.')),
                ('explanation', models.TextField()),
                ('revision_tips', models.TextField(blank=True)),
                ('practice_prompt', models.TextField(blank=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revision_knowledge_entries', to='learning.programme')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revision_knowledge_entries', to='learning.curriculumunit')),
            ],
            options={
                'ordering': ['priority', 'topic_title'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotAnswerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.CharField(choices=[('helpful', 'Helpful'), ('not_helpful', 'Not Helpful')], max_length=20)),
                ('query_text', models.TextField(blank=True)),
                ('answer_text', models.TextField()),
                ('visual_cue', models.CharField(blank=True, max_length=64)),
                ('navigation_target', models.CharField(blank=True, max_length=64)),
                ('needs_review', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_entries', to='chatbot.conversation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_chatbot_feedback', to=settings.AUTH_USER_MODEL)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='chatbot.turn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'turn')},
            },
        ),
    ]
