"""Declarative Year 1 curriculum for Beadwork Academy's MVP vertical slice:
Tool Orientation -> Colors & Color Theory -> Starting a Piece & the Mat
Project. Loaded idempotently by `python manage.py seed_curriculum`.

Media URLs are placeholders (`https://media.beadworkacademy.example/...`) -
swap them for real hosted video/photo assets before shipping; the seed
command is safe to rerun after editing these values.
"""

MODULES = [
    {
        "code": "BEAD-M1",
        "title": "Tool Orientation",
        "order": 1,
        "year_index": 1,
        "summary": "Get to know every tool and material before we start beading.",
        "unlocks_after": None,
        "lessons": [
            {
                "code": "BEAD-M1-L1",
                "title": "Meet your needle",
                "order": 1,
                "is_new_technique": True,
                "estimated_minutes": 6,
                "instructions_text": "Watch the video, then find your own needle and try each step.",
                "intro_video_url": "https://media.beadworkacademy.example/videos/m1-l1-needle.mp4",
                "steps": [
                    {"order": 1, "caption": "Hold the needle gently between two fingers.",
                     "photo_url": "https://media.beadworkacademy.example/photos/m1-l1-step1.jpg"},
                    {"order": 2, "caption": "Find the sharp end and the eye (the little hole for thread).",
                     "photo_url": "https://media.beadworkacademy.example/photos/m1-l1-step2.jpg"},
                    {"order": 3, "caption": "Practice picking the needle up and putting it down safely.",
                     "photo_url": "https://media.beadworkacademy.example/photos/m1-l1-step3.jpg"},
                ],
            },
            {
                "code": "BEAD-M1-L2",
                "title": "Meet your thread and wire",
                "order": 2,
                "is_new_technique": True,
                "estimated_minutes": 6,
                "intro_video_url": "https://media.beadworkacademy.example/videos/m1-l2-thread.mp4",
                "steps": [
                    {"order": 1, "caption": "Feel the thread - it bends easily.",
                     "photo_url": "https://media.beadworkacademy.example/photos/m1-l2-step1.jpg"},
                    {"order": 2, "caption": "Feel the wire - it holds its shape.",
                     "photo_url": "https://media.beadworkacademy.example/photos/m1-l2-step2.jpg"},
                    {"order": 3, "caption": "Practice threading the needle with an adult or on your own.",
                     "photo_url": "https://media.beadworkacademy.example/photos/m1-l2-step3.jpg"},
                ],
            },
            {
                "code": "BEAD-M1-L3",
                "title": "Meet your beads",
                "order": 3,
                "is_new_technique": True,
                "estimated_minutes": 8,
                "intro_video_url": "https://media.beadworkacademy.example/videos/m1-l3-beads.mp4",
                "steps": [
                    {"order": 1, "caption": "Pour a few beads into a shallow dish.",
                     "photo_url": "https://media.beadworkacademy.example/photos/m1-l3-step1.jpg"},
                    {"order": 2, "caption": "Pick up one bead at a time with your fingers.",
                     "photo_url": "https://media.beadworkacademy.example/photos/m1-l3-step2.jpg"},
                    {"order": 3, "caption": "Practice threading 5 beads onto your needle.",
                     "photo_url": "https://media.beadworkacademy.example/photos/m1-l3-step3.jpg"},
                ],
            },
            {
                "code": "BEAD-M1-L4",
                "title": "Meet your board and clasp",
                "order": 4,
                "is_new_technique": True,
                "estimated_minutes": 6,
                "intro_video_url": "https://media.beadworkacademy.example/videos/m1-l4-board.mp4",
                "steps": [
                    {"order": 1, "caption": "Find the bead board with its little grooves.",
                     "photo_url": "https://media.beadworkacademy.example/photos/m1-l4-step1.jpg"},
                    {"order": 2, "caption": "Lay a few beads into one groove in a line.",
                     "photo_url": "https://media.beadworkacademy.example/photos/m1-l4-step2.jpg"},
                    {"order": 3, "caption": "Open and close a clasp with your fingers.",
                     "photo_url": "https://media.beadworkacademy.example/photos/m1-l4-step3.jpg"},
                ],
            },
        ],
    },
    {
        "code": "BEAD-M2",
        "title": "Colors & Color Theory",
        "order": 2,
        "year_index": 1,
        "summary": "Learn which colors look good together before choosing colors for a project.",
        "unlocks_after": "BEAD-M1",
        "lessons": [
            {
                "code": "BEAD-M2-L1",
                "title": "The color wheel",
                "order": 1,
                "is_new_technique": True,
                "estimated_minutes": 8,
                "intro_video_url": "https://media.beadworkacademy.example/videos/m2-l1-wheel.mp4",
                "steps": [
                    {"order": 1, "caption": "Look at the color wheel - red, orange, yellow, green, blue, purple.",
                     "photo_url": "https://media.beadworkacademy.example/photos/m2-l1-step1.jpg"},
                    {"order": 2, "caption": "Point to your favorite color on the wheel.",
                     "photo_url": "https://media.beadworkacademy.example/photos/m2-l1-step2.jpg"},
                    {"order": 3, "caption": "Sort a handful of beads by color into small cups.",
                     "photo_url": "https://media.beadworkacademy.example/photos/m2-l1-step3.jpg"},
                ],
            },
            {
                "code": "BEAD-M2-L2",
                "title": "Picking colors that work together",
                "order": 2,
                "is_new_technique": False,
                "estimated_minutes": 10,
                "instructions_text": "No new video this time - practice what you just learned.",
                "steps": [
                    {"order": 1, "caption": "Try two colors that sit next to each other on the wheel (e.g. blue + green).",
                     "photo_url": "https://media.beadworkacademy.example/photos/m2-l2-step1.jpg"},
                    {"order": 2, "caption": "Try two colors that sit across from each other on the wheel (e.g. red + green).",
                     "photo_url": "https://media.beadworkacademy.example/photos/m2-l2-step2.jpg"},
                    {"order": 3, "caption": "Pick your favorite pairing for your mat project.",
                     "photo_url": "https://media.beadworkacademy.example/photos/m2-l2-step3.jpg"},
                ],
            },
        ],
    },
    {
        "code": "BEAD-M3",
        "title": "Starting a Piece & the Mat Project",
        "order": 3,
        "year_index": 1,
        "summary": "Learn the starting technique, then practice it until your first mat is finished.",
        "unlocks_after": "BEAD-M2",
        "lessons": [
            {
                "code": "BEAD-M3-L1",
                "title": "How to start: anchoring your first row",
                "order": 1,
                "is_new_technique": True,
                "estimated_minutes": 12,
                "intro_video_url": "https://media.beadworkacademy.example/videos/m3-l1-start.mp4",
                "steps": [
                    {"order": 1, "caption": "Tie a secure knot at the end of your thread.",
                     "photo_url": "https://media.beadworkacademy.example/photos/m3-l1-step1.jpg"},
                    {"order": 2, "caption": "Thread your first row of beads onto the board's guide line.",
                     "photo_url": "https://media.beadworkacademy.example/photos/m3-l1-step2.jpg"},
                    {"order": 3, "caption": "Check your row is straight before moving on.",
                     "photo_url": "https://media.beadworkacademy.example/photos/m3-l1-step3.jpg"},
                ],
            },
            {
                "code": "BEAD-M3-L2",
                "title": "Practice: row 2",
                "order": 2,
                "is_new_technique": False,
                "estimated_minutes": 10,
                "instructions_text": "Same technique as last time - let's repeat it to build the habit.",
                "steps": [
                    {"order": 1, "caption": "Add your second row using the same starting technique.",
                     "photo_url": "https://media.beadworkacademy.example/photos/m3-l2-step1.jpg"},
                    {"order": 2, "caption": "Use the color pairing you picked in Module 2.",
                     "photo_url": "https://media.beadworkacademy.example/photos/m3-l2-step2.jpg"},
                ],
            },
            {
                "code": "BEAD-M3-L3",
                "title": "Practice: row 3 and beyond",
                "order": 3,
                "is_new_technique": False,
                "estimated_minutes": 10,
                "instructions_text": "Keep repeating - practice makes this feel easy.",
                "steps": [
                    {"order": 1, "caption": "Keep adding rows until your mat is the size you want.",
                     "photo_url": "https://media.beadworkacademy.example/photos/m3-l3-step1.jpg"},
                    {"order": 2, "caption": "Ask for help if a row comes loose - that's normal while learning!",
                     "photo_url": "https://media.beadworkacademy.example/photos/m3-l3-step2.jpg"},
                ],
            },
            {
                "code": "BEAD-M3-L4",
                "title": "Finishing your mat",
                "order": 4,
                "is_new_technique": False,
                "estimated_minutes": 10,
                "instructions_text": "Tie off your thread and admire your finished mat!",
                "steps": [
                    {"order": 1, "caption": "Tie a secure knot to finish the last row.",
                     "photo_url": "https://media.beadworkacademy.example/photos/m3-l4-step1.jpg"},
                    {"order": 2, "caption": "Trim any extra thread carefully.",
                     "photo_url": "https://media.beadworkacademy.example/photos/m3-l4-step2.jpg"},
                ],
                "milestone": {
                    "code": "BEAD-MILESTONE-MAT",
                    "title": "Finished my first mat",
                    "instructions_for_learner": "Take a photo of your finished mat. You can also record a short video showing it off!",
                    "requires_video": False,
                },
            },
        ],
    },
]
