# Generated by Django 6.0.1 on 2026-07-14 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('instructions_text', models.TextField(blank=True)),
                ('intro_video_url', models.URLField(blank=True)),
                ('is_new_technique', models.BooleanField(default=False, help_text="If true, the lesson player shows intro_video_url the first time; otherwise it's a practice repeat (photo-steps only).")),
                ('estimated_minutes', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['module__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LessonStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('caption', models.CharField(max_length=300)),
                ('photo_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='curriculum/steps/')),
                ('is_checklist_item', models.BooleanField(default=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='skillapp_core_curriculum.lesson')),
            ],
            options={
                'ordering': ['lesson_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('year_index', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unlocks_after', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_by', to='skillapp_core_curriculum.module')),
            ],
            options={
                'ordering': ['year_index', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('instructions_for_learner', models.TextField(blank=True)),
                ('requires_video', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='skillapp_core_curriculum.lesson')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='skillapp_core_curriculum.module')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='skillapp_core_curriculum.module'),
        ),
    ]
