# Generated by Django 6.0.1 on 2026-01-15 11:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cohort_year',
        ),
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
