# Generated by Django 6.0.1 on 2026-07-14 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skillapp_core_curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_count', models.PositiveIntegerField(default=1)),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_completions', to=settings.AUTH_USER_MODEL)),
                ('lesson_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='skillapp_core_curriculum.lessonstep')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('learner', 'lesson_step'), name='unique_learner_step_completion')],
            },
        ),
        migrations.CreateModel(
            name='LearnerLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps_completed', models.PositiveIntegerField(default=0)),
                ('steps_total', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_progress', to='skillapp_core_curriculum.lesson')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('learner', 'lesson'), name='unique_learner_lesson_progress')],
            },
        ),
    ]
