# Generated by Django 5.2.5 on 2026-03-22 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_approvalrequest_datagovernancepolicy_reportrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBundleImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundle_name', models.CharField(max_length=128, unique=True)),
                ('bundle_sha256', models.CharField(max_length=64)),
                ('source_path', models.CharField(blank=True, default='', max_length=255)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('loaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-loaded_at', '-updated_at'],
            },
        ),
    ]
